"""Packed exact topology input. Its entirety is regenerated by the main replay."""
from pathlib import Path
import struct,gzip,json
if not __debug__:raise RuntimeError('Run without -O')
ROOT=Path(__file__).resolve().parents[1];ENUM=ROOT/'enumeration'
class Store:
 def __init__(self):
  self.data={};self.counts={}
  for B in range(12,20):
   raw=gzip.decompress((ENUM/f'survivors20_B{B}.bin.gz').read_bytes());assert len(raw)>=16
   tag,N,bb,n=struct.unpack_from('<4sIII',raw);assert tag==b'D20T' and N==20 and bb==B
   assert len(raw)==16+n*4*(38-B)
   self.data[B]=raw;self.counts[B]=n
 def masks(self,B,j):
  assert type(B)is int and type(j)is int and B in self.counts and 0<=j<self.counts[B]
  k=38-B;ms=struct.unpack_from('<'+'I'*k,self.data[B],16+j*4*k)
  assert list(ms)==sorted(set(ms)) and all(0<m<(1<<20) and m.bit_count()==3 for m in ms)
  return ms
 def faces(self,B,j):return [[v for v in range(20) if m>>v&1] for m in self.masks(B,j)]
 def keys(self):
  for B in range(12,20):
   for j in range(self.counts[B]):yield B,j
